### ISSUE TITLE
Typing error on opening course screen

### ISSUE THREAD

**Issue by kgibson5** [DMIT-2018/StudentNotes#12] opened 2015-09-15 01:26 UTC
Repsonsibility should be responsibility. In the associated paragraph, the word 'imperitive' is spelled incorrectly. Should be imperative.

Under 'Authors' the word 'digitial' is spelled incorrectly. Should be digital.

**Comment by dgilleland** [comment] 2015-09-17 16:12
Duplicate of #11 and #15

**Closed by dgilleland** 2015-09-17 16:12 UTC
