### ISSUE TITLE
Typing error on opening course screen

### ISSUE THREAD

**Issue by dwelchnait** [DMIT-2018/StudentNotes#14] opened 2015-09-15 01:26 UTC
Repsonsibility should be Responsibility

with the associate paragraph the word  --  imperitive -- is also has a spelling error

Under Authors

Digitial should be Digital

**Comment by dgilleland** [comment] 2015-09-17 16:13
Duplicate of #11 and #15

**Closed by dgilleland** 2015-09-17 16:13 UTC
