### ISSUE TITLE
Typing error on opening course screen

### ISSUE THREAD

**Issue by ssenthilkumar1** [DMIT-2018/StudentNotes#17] opened 2015-09-15 01:26 UTC
Repsonibility should be Responsibility
with associate paragraph the word -- imperitive  -- also has spelling error

under Authors - Digitial is also mispelled

**Comment by dgilleland** [comment] 2015-09-17 16:13
Duplicate of #11 and #15

**Closed by dgilleland** 2015-09-17 16:13 UTC
