### ISSUE TITLE
Typing error on opening course screen

### ISSUE THREAD

**Issue by swu18** [DMIT-2018/StudentNotes#23] opened 2015-09-15 01:27 UTC
Repsonsibility should be Responsibility
with this associate paragraph the word --imperitive is also has a spelling error
it should be imperative 

Under Authors:
Digitial should be Digital

**Comment by dgilleland** [comment] 2015-09-17 16:17
Duplicate of #11 and #15

**Closed by dgilleland** 2015-09-17 16:17 UTC
