### ISSUE TITLE
Spelling error on course introduction page.

### ISSUE THREAD

**Issue by JordanBandur** [DMIT-2018/StudentNotes#13] opened 2015-09-15 01:26 UTC
"Repsonsibility" should be Responsibility. In the associate paragraph, the word "imperitive" should be imperative. Lastly under the Authors section the word " Digitial" should be  Digital.

**Comment by dgilleland** [comment] 2015-09-17 16:13
Duplicate of #11 and #15

**Closed by dgilleland** 2015-09-17 16:13 UTC
