### ISSUE TITLE
Typing error on opening course screen

### ISSUE THREAD

**Issue by ferpelo1** [DMIT-2018/StudentNotes#16] opened 2015-09-15 01:26 UTC
Change Repsonsibility to Responsibility

with the associate paragraph the word -- imperitive -- is also has a spelling error

under Authors

Digitial should be Digital

**Comment by dgilleland** [comment] 2015-09-17 16:13
Duplicate of #11 and #15

**Closed by dgilleland** 2015-09-17 16:13 UTC
